#:schema node_modules/@deco/workers-runtime/config-schema.json
name = "studio"
main = "main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]
scope = "lucis"

[assets]
directory = "./view-build"
binding = "ASSETS"

[deco]
workspace = "lucis"
enable_workflows = true
local = false

[[deco.bindings]]
name = "GITHUB_LUCIS"
type = "mcp"
integration_id = "i:066a94fc-b0a6-43be-986a-2f0df713fea4"

[[migrations]]
tag = "v1"
new_classes = [ "Workflow" ]

[durable_objects]
[[durable_objects.bindings]]
name = "DECO_CHAT_WORKFLOW_DO"
class_name = "Workflow"

[[rules]]
type = "Text"
globs = [ "**/*.sql" ]
fallthrough = true